from .src.extract_trim_filename import (
    NODE_CLASS_MAPPINGS as EXTRACT_TRIM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EXTRACT_TRIM_NODE_DISPLAY_NAME_MAPPINGS,
)
from .src.LoadImageWithFilename import (
    NODE_CLASS_MAPPINGS as LOAD_IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOAD_IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)

# Combine all node class mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(EXTRACT_TRIM_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LOAD_IMAGE_NODE_CLASS_MAPPINGS)

# Combine all node display name mappings
NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(EXTRACT_TRIM_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LOAD_IMAGE_NODE_DISPLAY_NAME_MAPPINGS)